# In child-profile-service/.github/workflows/ci-cd.yml
name: Child-Profile Service CI/CD (Test, Build, Push)

on:
  push:
    branches:
      - main # Sau branch-ul principal
  workflow_dispatch: # Permite declanșarea manuală

jobs:
  build-and-push-child-profile:
    runs-on: ubuntu-latest
    name: Build & Push Child-Profile Docker Image
    env:
      DOCKER_IMAGE_NAME: mariuspreda/child-profile-service # Numele imaginii Docker Hub

    steps:
      - name: Checkout child-profile source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (multi-platform)
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile 
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} 
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
